[package]
name = "privatefox"
version = "0.1.0"
edition = "2021"

build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winreg = "0.50.0"

[build-dependencies]
winres = "0.1.12"
